// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAgendamento.Repository.Data;

namespace SistemaAgendamento.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230210030415_primeiraTentativa")]
    partial class primeiraTentativa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Agenda", b =>
                {
                    b.Property<int>("IdAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AgendaAberta")
                        .IsRequired()
                        .HasColumnType("char");

                    b.HasKey("IdAgenda");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Estabelecimento", b =>
                {
                    b.Property<int>("IdEstabelecimento")
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("NomeEstabelecimento")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeProfissional")
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdEstabelecimento");

                    b.ToTable("Estabelecimento");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Estabelecimento", b =>
                {
                    b.HasOne("SistemaAgendamento.Domain.Models.Agenda", "Agenda")
                        .WithOne("Estabelecimento")
                        .HasForeignKey("SistemaAgendamento.Domain.Models.Estabelecimento", "IdEstabelecimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Agenda", b =>
                {
                    b.Navigation("Estabelecimento");
                });
#pragma warning restore 612, 618
        }
    }
}
