// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAgendamento.Repository.Data;

namespace SistemaAgendamento.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230220225923_recriando base")]
    partial class recriandobase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Agenda", b =>
                {
                    b.Property<int>("IdAgenda")
                        .HasColumnType("int");

                    b.Property<string>("AgendaAberta")
                        .IsRequired()
                        .HasColumnType("char");

                    b.HasKey("IdAgenda");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Agendamento", b =>
                {
                    b.Property<byte[]>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("AgendaIdAgenda")
                        .HasColumnType("int");

                    b.Property<int>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiaHoraAgendamento")
                        .HasColumnType("DateTime");

                    b.Property<int>("StatusAgendamento")
                        .HasColumnType("int");

                    b.HasKey("IdAgendamento");

                    b.HasIndex("AgendaIdAgenda");

                    b.HasIndex("ClienteIdCliente");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Estabelecimento", b =>
                {
                    b.Property<int>("IdEstabelecimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasColumnType("char");

                    b.Property<string>("NomeEstabelecimento")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeProfissional")
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdEstabelecimento");

                    b.ToTable("Estabelecimento");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Agenda", b =>
                {
                    b.HasOne("SistemaAgendamento.Domain.Models.Estabelecimento", "Estabelecimento")
                        .WithOne("Agenda")
                        .HasForeignKey("SistemaAgendamento.Domain.Models.Agenda", "IdAgenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Agendamento", b =>
                {
                    b.HasOne("SistemaAgendamento.Domain.Models.Agenda", "Agenda")
                        .WithMany("Agendamentos")
                        .HasForeignKey("AgendaIdAgenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAgendamento.Domain.Models.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Agenda", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Cliente", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("SistemaAgendamento.Domain.Models.Estabelecimento", b =>
                {
                    b.Navigation("Agenda");
                });
#pragma warning restore 612, 618
        }
    }
}
